const fs = require('fs');

const enPath = 'd:/workspace/mattermost/webapp/channels/src/i18n/en.json';
const zhPath = 'd:/workspace/mattermost/webapp/channels/src/i18n/zh-CN.json';

const translations = {
    'admin.access_control.cel_editor.masked_values_tooltip': '由于此策略包含受限属性值，因此无法进行测试。',
    'admin.access_control.cel.masked_values_banner': '此表达式包含受限值。切换到简单模式即可编辑你有权访问的值。',
    'admin.access_control.delete_policy.error_title': '无法删除策略',
    'admin.access_control.delete_policy.generic_error': '删除策略失败。',
    'admin.access_control.delete_policy.masked_values': '你无法删除此策略，因为它包含你无权查看的属性值。',
    'admin.access_control.edit_policy.forbidden': '你无权对此策略进行此更改。请联系系统管理员获取帮助。',
    'admin.access_control.edit_policy.invalid_value': '无效值。',
    'admin.access_control.edit_policy.self_exclusion': '你不满足此策略中的一个或多个条件。请联系系统管理员获取帮助。',
    'admin.access_control.masked_chip.aria_label': '你无权查看的隐藏值',
    'admin.access_control.masked_chip.tooltip': '一个或多个受限值',
    'admin.access_control.policy.edit_policy.delete_policy.masked_values_warning.text': '删除此策略可能会影响你无法完全核实的用户访问权限。',
    'admin.access_control.policy.edit_policy.delete_policy.masked_values_warning.title': '此策略包含受限值，无法删除',
    'admin.access_control.policy.edit_policy.masked_values_warning.text': '某些规则包含你无法查看的属性值。编辑或删除这些规则可能会以你无法完全预见的方式改变谁可以访问。',
    'admin.access_control.policy.edit_policy.masked_values_warning.title': '此策略包含受限值',
    'admin.access_control.policy.edit_policy.mixed_channels.text': '在私人频道中，只有匹配的用户可以加入，不匹配的成员会被移除。在公开频道中，匹配的用户会被推荐或自动添加，但频道仍对所有人开放。',
    'admin.access_control.policy.edit_policy.mixed_channels.title': '成员策略对公开频道和私人频道的影响不同',
    'admin.access_control.simulate_access.activity.partial': '{total, plural, one {共 # 个会话，其中 {denied} 个被拒绝} other {共 # 个会话，其中 {denied} 个被拒绝}}',
    'admin.access_control.simulate_access.activity.total': '{total, plural, one {# 个会话} other {# 个会话}}',
    'admin.access_control.simulate_access.blame.channel_policy': '父级策略',
    'admin.access_control.simulate_access.blame.no_applicable_policy': '该策略不适用于此用户',
    'admin.access_control.simulate_access.blame.no_applicable_rule': '此规则不适用于此用户',
    'admin.access_control.simulate_access.blame.peer_policy': '另一条策略',
    'admin.access_control.simulate_access.blame.sibling_rule': '另一条规则',
    'admin.access_control.simulate_access.blame.sibling_saved': '另一条规则',
    'admin.access_control.simulate_access.blame.system_permission': '系统策略',
    'admin.access_control.simulate_access.blame.this_rule': '此规则',
    'admin.access_control.simulate_access.chip.allow': '允许',
    'admin.access_control.simulate_access.chip.allow_with_blame': '允许 · {source}',
    'admin.access_control.simulate_access.chip.deny': '拒绝',
    'admin.access_control.simulate_access.chip.deny_with_blame': '拒绝 · {source}',
    'admin.access_control.simulate_access.chip.pending': '正在评估…',
    'admin.access_control.simulate_access.chip.stacked.allowed': '允许',
    'admin.access_control.simulate_access.chip.stacked.denied': '拒绝',
    'admin.access_control.simulate_access.chip.stacked.mixed': '混合',
    'admin.access_control.simulate_access.chip.stacked.not_applicable': '策略不适用',
    'admin.access_control.simulate_access.col.actions': '操作',
    'admin.access_control.simulate_access.col.recent_activity': '最近活动',
    'admin.access_control.simulate_access.col.result': '结果',
    'admin.access_control.simulate_access.col.user': '用户',
    'admin.access_control.simulate_access.details.combined_explainer': '这些规则通过 OR 连接。只要其中任意一条匹配即可允许访问；此追踪会将它们合并显示。',
    'admin.access_control.simulate_access.details.combined_label': '合并评估',
    'admin.access_control.simulate_access.details.combined_label_with_role': '角色 {role} 的合并评估',
    'admin.access_control.simulate_access.details.hide_trace': '隐藏评估轨迹',
    'admin.access_control.simulate_access.details.multi_policy_explainer': '{count, plural, one {# 条策略} other {# 条策略}} 导致了这次拒绝。下方编号部分会依次显示每条策略。',
    'admin.access_control.simulate_access.details.multi_policy_explainer_mixed': '{denyCount, plural, one {# 条策略} other {# 条策略}} 拒绝；{allowCount, plural, one {# 条策略} other {# 条策略}} 允许。同一作用域上的多条策略按“拒绝优先”组合，因此只要有任意一条拒绝，整体结果即为拒绝。',
    'admin.access_control.simulate_access.details.policy_allowed': '允许',
    'admin.access_control.simulate_access.details.policy_denied': '拒绝',
    'admin.access_control.simulate_access.details.policy_label': '策略：{name}',
    'admin.access_control.simulate_access.details.rule_label': '规则：{name}',
    'admin.access_control.simulate_access.details.session_attributes': '会话属性',
    'admin.access_control.simulate_access.details.show_contributing_rules': '显示贡献规则',
    'admin.access_control.simulate_access.details.show_trace': '显示评估轨迹',
    'admin.access_control.simulate_access.details.title': '决策详情',
    'admin.access_control.simulate_access.details.trace.actual': '实际值：{value}',
    'admin.access_control.simulate_access.details.trace.and': '以下所有条件都必须成立（AND）',
    'admin.access_control.simulate_access.details.trace.not': '以下条件都不能成立（NOT）',
    'admin.access_control.simulate_access.details.trace.or': '以下任一条件可以成立（OR）',
    'admin.access_control.simulate_access.details.trace.unknown': '未知的复合评估',
    'admin.access_control.simulate_access.details.user_attributes': '用户属性',
    'admin.access_control.simulate_access.details.your_policy_allowed': '你的策略：允许',
    'admin.access_control.simulate_access.details.your_policy_denied': '你的策略：拒绝',
    'admin.access_control.simulate_access.editor.apply': '应用',
    'admin.access_control.simulate_access.editor.cancel': '取消',
    'admin.access_control.simulate_access.editor.description': '覆盖本次模拟使用的值。更改仅对这次运行生效。',
    'admin.access_control.simulate_access.editor.empty': '尚未配置任何会话属性。',
    'admin.access_control.simulate_access.editor.title': '编辑 {displayName} 的会话属性值',
    'admin.access_control.simulate_access.evaluate_against': '评估范围',
    'admin.access_control.simulate_access.load_error': '无法加载用户。请尝试关闭并重新打开该弹窗。',
    'admin.access_control.simulate_access.no_candidates': '此规则范围内没有可供模拟的用户。',
    'admin.access_control.simulate_access.no_search_results': '没有用户匹配此搜索。',
    'admin.access_control.simulate_access.pagination.next': '下一页',
    'admin.access_control.simulate_access.pagination.previous': '上一页',
    'admin.access_control.simulate_access.permission_filter.all': '所有权限',
    'admin.access_control.simulate_access.permission_filter.label': '权限',
    'admin.access_control.simulate_access.row.edit': '编辑会话属性值',
    'admin.access_control.simulate_access.scope.all': '所有策略',
    'admin.access_control.simulate_access.scope.this_rule': '仅此规则',
    'admin.access_control.simulate_access.search_aria': '搜索要模拟的用户',
    'admin.access_control.simulate_access.search_placeholder': '搜索用户',
    'admin.access_control.simulate_access.session.last_active': '最近活跃于 {ts}',
    'admin.access_control.simulate_access.session.last_active_unknown': '最近活跃 —',
    'admin.access_control.simulate_access.simulate_error': '无法评估策略。正在显示之前的结果。',
    'admin.access_control.simulate_access.subtitle': '搜索并分页浏览用户，以便根据所选范围进行评估。每一行显示该用户最近一次会话中该操作是否会被允许。',
    'admin.access_control.simulate_access.title': '模拟访问',
    'admin.classification_markings.error.global_banner_level_missing': '全局分类横幅配置的级别已不存在。请选择当前分类级别中仍存在的级别。',
    'admin.classification_markings.error.global_banner_no_level': '启用全局横幅时，必须选择一个全局分类级别。',
    'admin.classification_markings.global_banner.enable.description': '为系统范围的分类显示全局横幅。',
    'admin.classification_markings.global_banner.enable.false': '否',
    'admin.classification_markings.global_banner.enable.title': '全局分类横幅',
    'admin.classification_markings.global_banner.enable.true': '是',
    'admin.classification_markings.global_banner.level.description': '选择要显示在全局横幅上的分类级别。横幅文本和颜色由所选级别决定。',
    'admin.classification_markings.global_banner.level.missing_error': '之前选择的级别已不存在。请从当前分类级别中选择一个级别。',
    'admin.classification_markings.global_banner.level.title': '全局分类级别',
    'admin.classification_markings.global_banner.placement.title': '横幅可见性',
    'admin.classification_markings.global_banner.placement.top': '仅顶部',
    'admin.classification_markings.global_banner.placement.top_and_bottom': '顶部和底部',
    'admin.classification_markings.global_banner.section_description': '配置全局分类横幅',
    'admin.classification_markings.global_banner.section_title': '全局分类指示器',
    'admin.data_spillage_feature_discovery.desc': '设置消息隔离功能，让指定的内容审核员决定保留还是移除这些消息。',
    'admin.data_spillage_feature_discovery.title': '使用 Mattermost Enterprise Advanced 处理数据泄露',
    'admin.filestore.connectionTest': '测试连接',
    'admin.filestore.testFail': '连接失败：{error}',
    'admin.filestore.testing': '正在测试...',
    'admin.filestore.testSuccess': '连接成功',
    'admin.image.azureAccessKeyDescription': '你的 Azure 存储账户的共享密钥。',
    'admin.image.azureAccessKeyExample': '例如："9MZbtYgfq18PJ8PbRaJ5u91IH8izHvReTbcuQzMl+So="',
    'admin.image.azureAccessKeyTitle': 'Azure 存储账户密钥：',
    'admin.image.azureAuthModeDefaultCredential': '默认凭据（Microsoft Entra ID）',
    'admin.image.azureAuthModeDescription': '"共享密钥" 使用存储账户访问密钥为请求签名。\n\n"默认凭据（Microsoft Entra ID）" 从主机环境读取身份信息，例如 Azure 托管部署上的托管身份、工作负载身份、服务主体环境变量，或本地开发时的 "az login"。无需访问密钥。',
    'admin.image.azureAuthModeSharedKey': '共享密钥',
    'admin.image.azureAuthModeTitle': 'Azure 身份验证：',
    'admin.image.azureCloudCommercial': 'Azure 公有云',
    'admin.image.azureCloudCustom': '自定义端点',
    'admin.image.azureCloudDescription': '要连接的 Azure 云。选择 "Azure 公有云" 或 "Azure 政府云" 时，将使用该云的已知端点；此时只需提供存储账户名称。选择 "自定义端点" 可指向任意主机，例如 Azurite、反向代理，或其他 Azure 云（例如 Azure 中国）。',
    'admin.image.azureCloudGovernment': 'Azure 政府云',
    'admin.image.azureCloudTitle': 'Azure 云：',
    'admin.image.azureContainerDescription': 'Azure 存储账户中容器的名称。',
    'admin.image.azureContainerExample': '例如："mattermost-media"',
    'admin.image.azureContainerExportDescription': 'Azure 存储账户中容器的名称。',
    'admin.image.azureContainerExportExample': '例如："mattermost-export"',
    'admin.image.azureContainerTitle': 'Azure 容器：',
    'admin.image.azureEndpointDescription': '完整的 Blob 服务 URL，包括协议和存储账户。Mattermost 不会修改此 URL，因此存储账户必须已经嵌入主机名中（虚拟主机样式，例如 "https://acmemattermost.blob.core.chinacloudapi.cn/"），或嵌入路径中（路径样式，例如 "http://localhost:10000/devstoreaccount1/"）。共享密钥身份验证会针对该 URL 指向的主机进行签名，因此请确保它实际提供上面命名的存储账户服务。',
    'admin.image.azureEndpointExample': '例如："http://localhost:10000/devstoreaccount1/"',
    'admin.image.azureEndpointTitle': '自定义 Azure 端点：',
    'admin.image.azurePathPrefixDescription': 'Azure 容器中 Blob 使用的可选路径前缀。',
    'admin.image.azurePathPrefixExample': '例如："files/"，或留空',
    'admin.image.azurePathPrefixTitle': 'Azure 路径前缀：',
    'admin.image.azureRequestTimeoutDescription': '在 Azure Blob 存储响应前等待的毫秒数，超时后请求失败。',
    'admin.image.azureRequestTimeoutExample': '例如："30000"',
    'admin.image.azureRequestTimeoutTitle': 'Azure 请求超时（毫秒）：',
    'admin.image.azureSSLDescription': '为 false 时，允许与 Azure Blob 存储建立不安全连接。默认仅允许安全连接。对于“自定义端点”云选项将忽略此设置（协议已包含在端点 URL 中）。',
    'admin.image.azureSSLTitle': '启用安全的 Azure Blob 存储连接：',
    'admin.image.azureStorageAccountDescription': '你的 Azure 存储账户名称。',
    'admin.image.azureStorageAccountExample': '例如："mattermoststorage"',
    'admin.image.azureStorageAccountTitle': 'Azure 存储账户：',
    'admin.image.storeAzureBlob': 'Azure Blob 存储',
    'admin.mobileSecurity.ephemeralMode_feature_discovery.description': '在 Mattermost Enterprise Advanced 中，你可以启用移动端临时模式，以在移动设备上执行数据持久化策略。可配置断开连接超时、离线数据保留时间和自动缓存清理。',
    'admin.mobileSecurity.ephemeralMode_feature_discovery.title': '通过移动端临时模式控制移动数据持久化',
    'admin.mobileSecurity.ephemeralMode.autoCacheCleanup.placeholder': '例如：7',
    'admin.mobileSecurity.ephemeralMode.autoCacheCleanup.range': '必须是 0 到 60 天之间的数字。',
    'admin.mobileSecurity.ephemeralMode.autoCacheCleanupDescription': '控制设备上任意缓存内容的最大保留时长，与连接状态无关。可防止敏感数据无限累积。设为 0 表示零持久化模式，即内容永不写入磁盘。',
    'admin.mobileSecurity.ephemeralMode.autoCacheCleanupTitle': '自动缓存清理（天）：',
    'admin.mobileSecurity.ephemeralMode.banner': '这些设置的更改会实时下发到已连接的设备。离线设备将在重新与服务器建立连接前继续按其上次已知设置运行。计时器状态会在应用和设备重启后保留。',
    'admin.mobileSecurity.ephemeralMode.disconnectionTimeout.placeholder': '例如：60',
    'admin.mobileSecurity.ephemeralMode.disconnectionTimeout.range': '必须是 0 到 600 秒（10 分钟）之间的数字。',
    'admin.mobileSecurity.ephemeralMode.disconnectionTimeoutDescription': '设备与服务器断开连接后，在被视为离线前的宽限时间。可帮助避免短暂网络中断导致误触发。不建议设置为小于 5 的值。',
    'admin.mobileSecurity.ephemeralMode.disconnectionTimeoutTitle': '断开连接超时（秒）：',
    'admin.mobileSecurity.ephemeralMode.enableDescription': '启用后，移动客户端将遵循服务器配置的临时数据策略。断开连接的设备会根据配置的计时器清理缓存数据。',
    'admin.mobileSecurity.ephemeralMode.enableTitle': '启用移动端临时模式：',
    'admin.mobileSecurity.ephemeralMode.offlinePersistence.disabled': '设备离线后缓存内容的保留时长。计时器到期后，缓存内容将被删除，但会保留会话凭据。设为 0 表示立即清理。要求已启用移动端临时模式，且自动缓存清理大于 0。',
    'admin.mobileSecurity.ephemeralMode.offlinePersistence.placeholder': '例如：24',
    'admin.mobileSecurity.ephemeralMode.offlinePersistence.range': '必须是 0 到 72 小时（3 天）之间的数字。',
    'admin.mobileSecurity.ephemeralMode.offlinePersistenceDescription': '设备离线后缓存内容的保留时长。计时器到期后，缓存内容将被删除，但会保留会话凭据。设为 0 表示立即清理。',
    'admin.mobileSecurity.ephemeralMode.offlinePersistenceTitle': '离线持久化计时器（小时）：',
    'admin.mobileSecurity.sections.ephemeralMode.description': '配置移动设备的数据持久化和缓存管理策略。',
    'admin.permission_policies.editor.simulate_rules': '模拟规则',
    'admin.support.reportAProblemTypeDescriptionLicensed': '默认情况下，从帮助菜单选择“报告问题”会打开一封预填好的邮件草稿，发送给 Mattermost 技术支持团队。你可以选择“自定义链接”或“电子邮件地址”为终端用户支持提供自定义 URL 或邮箱地址。选择“隐藏链接”会从应用中移除“报告问题”选项。',
    'admin.support.reportAProblemTypeDescriptionUnlicensed': '默认情况下，从帮助菜单选择“报告问题”会打开 [Mattermost 故障排查论坛](https://mattermost.com/pl/report_a_problem_unlicensed)。你可以选择“自定义链接”或“电子邮件地址”为终端用户支持提供自定义 URL 或邮箱地址。选择“隐藏链接”会从应用中移除“报告问题”选项。',
    'admin.system_properties.user_properties.table.display_name_header': '显示名称',
    'admin.system_properties.user_properties.table.display_name.input.label': '显示名称',
    'admin.system_properties.user_properties.table.identifier.tooltip': '策略中使用的 Common Expression Language (CEL) 标识符。只允许字母、数字和下划线。必须以字母或下划线开头。不允许使用 CEL 保留字。',
    'admin.system_properties.user_properties.table.name': '名称',
    'admin.system_properties.user_properties.table.validation.banner.name_invalid_cel': '高亮显示的“名称”不是有效标识符。只能使用字母、数字和下划线；必须以字母或下划线开头，并避免使用 CEL 保留字。',
    'admin.system_properties.user_properties.table.validation.banner.name_required': '{count, plural, one {# 个属性缺少名称} other {# 个属性缺少名称}}。请输入名称后继续。',
    'admin.system_properties.user_properties.table.validation.banner.name_taken': '高亮显示的“名称”已被其他属性使用。请选择其他名称后继续。',
    'admin.system_properties.user_properties.table.validation.banner.name_unique': '{count, plural, one {# 个属性使用了相同名称} other {# 个属性使用了相同名称}}。请更新高亮显示的名称，使每个属性都有唯一标识符。',
    'admin.system_properties.user_properties.table.validation.name_invalid_cel': '标识符必须以字母或下划线开头，并且只能包含字母、数字和下划线。不允许使用 CEL 保留字。',
    'admin.team.enableChannelCategorySortingDescription': '为 true 时，频道管理员在创建或编辑频道时可以选择默认侧边栏类别。新频道成员加入频道时，系统会自动为其创建一个包含该频道的类别。',
    'admin.team.enableChannelCategorySortingTitle': '频道类别排序：',
    'channel_modal.classification.banner_label': '横幅文本',
    'channel_modal.classification.banner_placeholder': '横幅文本',
    'channel_modal.classification.level_label': '分类级别',
    'channel_modal.classification.toggle_description': '启用后，此频道将显示分类标记。单个频道的分类级别不能低于全局分类级别。',
    'channel_modal.classification.toggle_label': '频道分类',
    'channel_settings.classification.description': '启用后，可为频道设置分类级别并配置指示器。',
    'channel_settings.classification.level_label': '分类级别',
    'channel_settings.classification.title': '分类',
    'channel_settings.permissions_policy.action.download': '下载文件',
    'channel_settings.permissions_policy.action.download.description': '允许用户从此频道下载附件',
    'channel_settings.permissions_policy.action.upload': '上传文件',
    'channel_settings.permissions_policy.action.upload.description': '允许用户在此频道的消息中附加文件',
    'channel_settings.permissions_policy.add_rule': '添加规则',
    'channel_settings.permissions_policy.column.name': '名称',
    'channel_settings.permissions_policy.column.permissions': '权限',
    'channel_settings.permissions_policy.editor.add': '添加规则',
    'channel_settings.permissions_policy.editor.add_title': '添加权限规则',
    'channel_settings.permissions_policy.editor.back': '返回规则列表',
    'channel_settings.permissions_policy.editor.cancel': '取消',
    'channel_settings.permissions_policy.editor.edit_title': '编辑权限规则',
    'channel_settings.permissions_policy.editor.save': '保存规则',
    'channel_settings.permissions_policy.empty': '还没有权限规则。点击“添加规则”即可创建。',
    'channel_settings.permissions_policy.empty_search': '没有规则与搜索条件匹配。',
    'channel_settings.permissions_policy.error.actions_required': '每条规则至少选择一个权限操作。',
    'channel_settings.permissions_policy.error.expression_required': '每条规则都需要一个属性表达式。',
    'channel_settings.permissions_policy.error.name_required': '每条权限规则都需要一个唯一名称。',
    'channel_settings.permissions_policy.error.name_unique': '规则名称“{name}”被重复使用。名称在此频道内必须唯一。',
    'channel_settings.permissions_policy.field.actions': '权限',
    'channel_settings.permissions_policy.field.actions_add': '添加权限',
    'channel_settings.permissions_policy.field.actions_add_menu_aria': '添加权限菜单',
    'channel_settings.permissions_policy.field.actions_column': '权限',
    'channel_settings.permissions_policy.field.actions_empty': '为此规则添加一项权限',
    'channel_settings.permissions_policy.field.actions_hint': '这些权限由此规则控制',
    'channel_settings.permissions_policy.field.actions_remove': '删除权限',
    'channel_settings.permissions_policy.field.expression': '用户属性条件',
    'channel_settings.permissions_policy.field.name': '名称',
    'channel_settings.permissions_policy.field.name_placeholder': '例如：阻止外部上传',
    'channel_settings.permissions_policy.field.role': '角色',
    'channel_settings.permissions_policy.field.role_hint': '此规则适用的频道范围角色',
    'channel_settings.permissions_policy.field.role_menu_aria': '角色选择菜单',
    'channel_settings.permissions_policy.form_error': '上述表单中存在错误',
    'channel_settings.permissions_policy.load_error': '加载此频道的权限策略失败。请尝试关闭并重新打开频道设置。',
    'channel_settings.permissions_policy.or_hint': '当多条规则适用于同一角色和操作时，只要其中任意一条允许，该用户就会被允许。即使此频道策略允许，系统级策略仍可能拒绝该权限。',
    'channel_settings.permissions_policy.pagination.next': '下一页',
    'channel_settings.permissions_policy.pagination.previous': '上一页',
    'channel_settings.permissions_policy.pagination.range': '{total} 中的 {start} - {end}',
    'channel_settings.permissions_policy.role.channel_admin': '频道管理员',
    'channel_settings.permissions_policy.role.channel_admin.description': '仅适用于频道管理员',
    'channel_settings.permissions_policy.role.channel_guest': '频道访客',
    'channel_settings.permissions_policy.role.channel_guest.description': '仅适用于此频道中的访客账户',
    'channel_settings.permissions_policy.role.channel_user': '频道成员',
    'channel_settings.permissions_policy.role.channel_user.description': '适用于普通频道成员。当不存在针对管理员的专用规则时，频道管理员会回退到此规则。',
    'channel_settings.permissions_policy.role.select': '选择角色',
    'channel_settings.permissions_policy.row.delete': '删除',
    'channel_settings.permissions_policy.row.edit': '编辑',
    'channel_settings.permissions_policy.row.menu_label': '规则操作',
    'channel_settings.permissions_policy.row.permissions_count': '{count, plural, one {# 项权限} other {# 项权限}}',
    'channel_settings.permissions_policy.row.unnamed': '（未命名规则）',
    'channel_settings.permissions_policy.save_error': '保存权限规则失败',
    'channel_settings.permissions_policy.search_aria': '按名称或权限搜索权限规则',
    'channel_settings.permissions_policy.search_placeholder': '按名称或权限搜索',
    'channel_settings.permissions_policy.section_title': '频道权限规则',
    'channel_settings.permissions_policy.system_banner': '系统范围的权限策略也可能影响此频道的访问决策。',
    'channel_settings.tab.permissions_policy': '权限策略',
    'data_spillage_report.download_report.button_text': '下载报告',
    'data_spillage_report.download_report.failed.button_text': '生成失败。请重试。',
    'data_spillage_report.download_report.generating.button_text': '正在生成报告…',
    'data_spillage_report.row.actions.label': '操作',
    'data_spillage_report.row.report.label': '报告',
    'default_category.create_new_prefix': '创建新类别：',
    'default_category.help_text': '设置用户加入频道时的默认侧边栏类别。',
    'default_category.label': '默认类别（可选）',
    'default_category.placeholder': '选择默认类别（可选）',
    'default_category.placeholder_focused': '选择类别或输入新类别',
    'feature_toast.tooltipCloseBtn': '关闭',
    'generic_icons.permissions_policy': '权限策略图标',
    'inline_action_button.executing': '正在执行...',
    'inline_action_button.timeout': '操作超时。请重试。',
    'installed_integrations.last_used': '上次使用于 {lastUsed, date, full}',
    'installed_integrations.never_used': '从未使用',
    'keep_remove_quarantined_content_modal.action_keep.generated.body': '报告现在应已开始下载到你的设备。下载完成后，你可以永久保留该消息。',
    'keep_remove_quarantined_content_modal.action_keep.generating.body': '请等待报告下载完成，然后再永久保留该消息。',
    'keep_remove_quarantined_content_modal.action_keep.permanent_button_text': '永久保留',
    'keep_remove_quarantined_content_modal.action_remove_without_report.button_text': '不下载报告直接移除',
    'keep_remove_quarantined_content_modal.action_remove_without_report.title': '不下载报告直接移除？',
    'keep_remove_quarantined_content_modal.action_remove.generated.body': '报告现在应已开始下载到你的设备。下载完成后，你可以永久移除该消息。',
    'keep_remove_quarantined_content_modal.action_remove.generating.body': '请等待报告下载完成，然后再永久移除该消息。一旦移除，将无法恢复该消息内容。',
    'keep_remove_quarantined_content_modal.action_remove.permanent_button_text': '永久移除',
    'keep_remove_quarantined_content_modal.action_remove.skip_confirm.body': '你正在未下载报告的情况下继续移除内容。之后生成的任何报告都不会包含原始消息内容。此操作无法撤销。',
    'keep_remove_quarantined_content_modal.back.button_text': '返回',
    'keep_remove_quarantined_content_modal.continue.button_text': '继续',
    'keep_remove_quarantined_content_modal.download_again.button_text': '再次下载',
    'keep_remove_quarantined_content_modal.download_report_checkbox.label': '下载隔离消息报告',
    'keep_remove_quarantined_content_modal.error.body': '我们无法生成并将报告下载到你的设备。',
    'keep_remove_quarantined_content_modal.error.title': '无法生成报告',
    'keep_remove_quarantined_content_modal.generated.title': '报告已生成',
    'keep_remove_quarantined_content_modal.generating.title': '正在生成报告…',
    'keep_remove_quarantined_content_modal.skip_report_download.button_text': '跳过报告下载',
    'keep_remove_quarantined_content_modal.try_again.button_text': '重试',
    'leave_policy_channel_modal.leave': '离开频道',
    'leave_policy_channel_modal.message': '你属于此频道的成员策略范围。如果离开，将不会被自动重新添加。',
    'leave_policy_channel_modal.mute_hint': '如果你想保留成员身份但不接收通知，可以改为将此频道静音。',
    'leave_policy_channel_modal.mute_instead': '改为静音',
    'leave_policy_channel_modal.title': '离开 {channel} 频道',
    'mark_all_as_read_modal.cancel': '取消',
    'mark_all_as_read_modal.checkbox': '不再询问我',
    'mark_all_as_read_modal.confirm': '全部标为已读',
    'mark_all_as_read_modal.message': '{shortcut} 会将此团队中频道、线程和私聊里的所有消息标记为已读。确定吗？',
    'mark_all_as_read_modal.title': '将所有消息标记为已读？',
    'mark_all_as_read_toast.button': '知道了',
    'mark_all_as_read_toast.message': '现在你可以使用 {shortcut} 将此团队中的所有消息标记为已读。别担心，系统会先让你确认。',
    'mark_all_as_read_toast.title': '用于清除未读的新快捷键',
    'shortcuts.msgs.mark_all_read': '将所有消息标记为已读：\tShift|Esc',
    'user.settings.advance.concurrentReactExperimental': '启用 Concurrent React（实验性）',
    'user.settings.advance.concurrentReactExperimentalDesc1': '当设为“开”时，将为开发环境启用 Concurrent React 支持。已知这可能引发问题，只有在你明确知道自己在做什么时才建议开启。',
    'user.settings.advance.concurrentReactExperimentalDesc2': '在此设置生效前，你可能需要刷新页面。',
};

const en = JSON.parse(fs.readFileSync(enPath, 'utf8'));
const zh = JSON.parse(fs.readFileSync(zhPath, 'utf8'));

const missing = Object.keys(en).filter((key) => !(key in zh));
const untranslated = missing.filter((key) => !(key in translations));
if (untranslated.length > 0) {
    throw new Error(`Missing translations for keys: ${untranslated.join(', ')}`);
}

const merged = {};
for (const [key, value] of Object.entries(en)) {
    merged[key] = zh[key] ?? translations[key] ?? value;
}

for (const [key, value] of Object.entries(zh)) {
    if (!(key in merged)) {
        merged[key] = value;
    }
}

fs.writeFileSync(zhPath, JSON.stringify(merged, null, 2) + '\n');
console.log(`Filled ${missing.length} missing zh-CN translations.`);
